include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_initializing_formals: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    use_null_aware_elements: ignore
    use_build_context_synchronously: ignore
